name: Run Pytest with Conda

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda
        with:
          python-version: '3.10'  # You can specify your desired Python version here
          auto-update-conda: true
          environment-file: mace-openmm.yml  # Points to the environment.yml in your repo
          activate-environment: test-env  # Name of the environment you will create

      - name: Install dependencies
        run: |
          conda install mamba
          mamba env update --file mace-openmm.yml --name test-env
          mamba install pytest

      - name: Run Pytest
        run: |
          source activate test-env
          pytest -s tests/
